Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,28 +43,13 @@ jobs:
           wget --directory-prefix .repo/local_manifests https://raw.githubusercontent.com/robertoviola-systemelectronics/meta-sysele-nxp-5.15.71/refs/heads/os-release-signing/manifest/astrial-5.15.71.xml
           repo sync
 
-      - name: Patch BitBake worker functionality
+      - name: Patch bitbake-worker
         run: |
-          cat > bitbake-worker.patch << 'EOF'
-          --- bitbake-worker.orig      2023-04-01 00:00:00.000000000 +0000
-          +++ bitbake-worker   2023-04-01 00:00:00.000000000 +0000
-          @@ -266,7 +266,11 @@
-               uid = worker.parent.worker_uid
-               gid = worker.parent.worker_gid
-               create_process_group = worker.parent.create_process_group
-          -    bb.utils.disable_network(uid, gid)
-          +    try:
-          +        bb.utils.disable_network(uid, gid)
-          +    except PermissionError:
-          +        bb.warn("Cannot disable network in this environment, continuing without network isolation")
-          +        pass
-               if worker.parent.umask:
-                   os.umask(worker.parent.umask)
-          EOF
-          
           BITBAKE_WORKER=$(find /home/runner/work/meta-sysele-nxp-5.15.71/meta-sysele-nxp-5.15.71/yocto-astrial/sources/poky/bitbake/bin -name "bitbake-worker")
           cp $BITBAKE_WORKER ${BITBAKE_WORKER}.bak
-          patch $BITBAKE_WORKER < bitbake-worker.patch || echo "Patch può aver fallito, ma continuiamo"
+          NETWORK_LINE=$(grep -n "disable_network" $BITBAKE_WORKER | head -1 | cut -d: -f1)
+          sed -i "${NETWORK_LINE}s/.*/    try:\n        bb.utils.disable_network(uid, gid)\n    except PermissionError:\n        bb.warn(\"Cannot disable network in this environment, continuing without isolation\")\n        pass/" $BITBAKE_WORKER
+          cat $BITBAKE_WORKER | grep -A5 "try:" || echo "Modifica non trovata"
 
       - name: Generate Build Signature
         run: |
